version: 2.1

jobs:
  test:
    docker:
      - image: python:3.13.2
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: python -m pip install --upgrade pip requests python-dotenv
      - run:
          name: Run Python Tests
          working_directory: Homework
          command: python -m unittest discover -s .

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
